class Uniforms
	{
		name = "Uniforms";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] =
		{
			"U_C_Journalist",
			"U_C_Poloshirt_blue",
			"U_C_Poloshirt_burgundy",
			"U_C_Poloshirt_salmon",
			"U_C_Poloshirt_stripped",
			"U_C_Poloshirt_tricolour",
			"U_C_Poor_1",
			"U_C_Poor_2",
			"U_C_Poor_shorts_1",
			"U_C_Scientist",
			"U_OrestesBody",
			"U_Rangemaster",
			"U_NikosAgedBody",
			"U_NikosBody",
			"U_Competitor",
			"U_B_CombatUniform_mcam",
			"U_B_CombatUniform_mcam_tshirt",
			"U_B_CombatUniform_mcam_vest",
			"U_B_CombatUniform_mcam_worn",
			"U_B_CTRG_1",
			"U_B_CTRG_2",
			"U_B_CTRG_3",
			"U_I_CombatUniform",
			"U_I_CombatUniform_shortsleeve",
			"U_I_CombatUniform_tshirt",
			"U_I_OfficerUniform",
			"U_O_CombatUniform_ocamo",
			"U_O_CombatUniform_oucamo",
			"U_O_OfficerUniform_ocamo",
			"U_B_SpecopsUniform_sgg",
			"U_O_SpecopsUniform_blk",
			"U_O_SpecopsUniform_ocamo",
			"U_I_G_Story_Protagonist_F",
			"Exile_Uniform_Woodland",
			"U_C_HunterBody_grn",
			"U_IG_Guerilla1_1",
			"U_IG_Guerilla2_1",
			"U_IG_Guerilla2_2",
			"U_IG_Guerilla2_3",
			"U_IG_Guerilla3_1",
			"U_BG_Guerilla2_1",
			"U_IG_Guerilla3_2",
			"U_BG_Guerrilla_6_1",
			"U_BG_Guerilla1_1",
			"U_BG_Guerilla2_2",
			"U_BG_Guerilla2_3",
			"U_BG_Guerilla3_1",
			"U_BG_leader",
			"U_IG_leader",
			"U_I_G_resistanceLeader_F",
			"U_B_FullGhillie_ard",
			"U_B_FullGhillie_lsh",
			"U_B_FullGhillie_sard",
			"U_B_GhillieSuit",
			"U_I_FullGhillie_ard",
			"U_I_FullGhillie_lsh",
			"U_I_FullGhillie_sard",
			"U_I_GhillieSuit",
			"U_O_FullGhillie_ard",
			"U_O_FullGhillie_lsh",
			"U_O_FullGhillie_sard",
			"U_O_GhillieSuit",
			"U_I_Wetsuit",
			"U_O_Wetsuit",
			"U_B_Wetsuit",
			"U_B_survival_uniform",
			"U_B_HeliPilotCoveralls",
			"U_I_HeliPilotCoveralls",
			"U_B_PilotCoveralls",
			"U_O_PilotCoveralls",
			"U_B_T_Soldier_F",
			"U_B_T_Soldier_AR_F",
			"U_B_T_Soldier_SL_F",
			"U_B_T_Sniper_F",
			"U_B_T_FullGhillie_tna_F",
			"U_B_CTRG_Soldier_F",
			"U_B_CTRG_Soldier_2_F",
			"U_B_CTRG_Soldier_3_F",
			"U_B_GEN_Soldier_F",
			"U_B_GEN_Commander_F",
			"U_O_T_Soldier_F",
			"U_O_T_Officer_F",
			"U_O_T_Sniper_F",
			"U_O_T_FullGhillie_tna_F",
			"U_O_V_Soldier_Viper_F",
			"U_O_V_Soldier_Viper_hex_F",
			"U_I_C_Soldier_Para_1_F",
			"U_I_C_Soldier_Para_2_F",
			"U_I_C_Soldier_Para_3_F",
			"U_I_C_Soldier_Para_4_F",
			"U_I_C_Soldier_Para_5_F",
			"U_I_C_Soldier_Bandit_1_F",
			"U_I_C_Soldier_Bandit_2_F",
			"U_I_C_Soldier_Bandit_3_F",
			"U_I_C_Soldier_Bandit_5_F",
			"U_I_C_Soldier_Camo_F",
			"U_C_man_sport_1_F",
			"U_C_man_sport_2_F",
			"U_C_man_sport_3_F",
			"U_C_Man_casual_1_F",
			"U_C_Man_casual_2_F",
			"U_C_Man_casual_3_F",
			"U_C_Man_casual_4_F",
			"U_C_Man_casual_5_F",
			"U_C_Man_casual_6_F",
			"U_B_CTRG_Soldier_urb_1_F",
			"U_B_CTRG_Soldier_urb_2_F",
			"U_B_CTRG_Soldier_urb_3_F",
			"U_C_CBRN_Suit_01_Blue_F",
			"U_C_CBRN_Suit_01_White_F",
			"rhs_uniform_emr_des_patchless",
			"rhs_uniform_emr_patchless",
			"rhs_uniform_flora_patchless",
			"rhs_uniform_flora_patchless_alt",
			"rhs_uniform_gorka_r_g",
			"rhs_uniform_gorka_r_y",
			"rhs_uniform_gorka_1_a",
			"rhs_uniform_abu",
			"rhs_uniform_acu_ocp",
			"rhs_uniform_acu_ucpd",
			"rhs_uniform_cu_ocp",
			"rhs_uniform_cu_ucp",
			"rhs_uniform_FROG01_d",
			"rhs_uniform_FROG01_wd",
			"rhs_uniform_g3_aor2",
			"rhs_uniform_g3_blk",
			"rhs_uniform_g3_m81",
			"rhs_uniform_g3_mc",
			"rhs_uniform_g3_rgr",
			"rhs_uniform_g3_tan",
			"rhsgref_uniform_gorka_1_f",
			"rhsgref_uniform_TLA_1",
			"rhsgref_uniform_TLA_2",
			"rhsgref_uniform_para_ttsko_mountain",
			"rhsgref_uniform_ttsko_forest",
			"rhsgref_uniform_altis_lizard_olive",
			"rhsgref_uniform_olive",
			"rhsgref_uniform_reed",
			"rhssaf_uniform_m10_digital_desert",
			"U_C_IDAP_Man_Tee_F",
			"U_C_ConstructionCoverall_Black_F",
			"U_Tank_green_F"
		};
	};

	class Vests
	{
		name = "Vests";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\vest_ca.paa";
		items[] =
		{
			"V_Press_F",
			"V_Rangemaster_belt",
			"V_TacVest_blk",
			"V_TacVest_blk_POLICE",
			"V_TacVest_brn",
			"V_TacVest_camo",
			"V_TacVest_khk",
			"V_TacVest_oli",
			"V_TacVestCamo_khk",
			"V_TacVestIR_blk",
			"V_I_G_resistanceLeader_F",
			"V_BandollierB_blk",
			"V_BandollierB_cbr",
			"V_BandollierB_khk",
			"V_BandollierB_oli",
			"V_BandollierB_rgr",
			"V_Chestrig_blk",
			"V_Chestrig_khk",
			"V_Chestrig_oli",
			"V_Chestrig_rgr",
			"V_HarnessO_brn",
			"V_HarnessO_gry",
			"V_HarnessOGL_brn",
			"V_HarnessOGL_gry",
			"V_HarnessOSpec_brn",
			"V_HarnessOSpec_gry",
			"V_PlateCarrier1_blk",
			"V_PlateCarrier1_rgr",
			"V_PlateCarrier2_rgr",
			"V_PlateCarrier3_rgr",
			"V_PlateCarrierGL_blk",
			"V_PlateCarrierGL_mtp",
			"V_PlateCarrierGL_rgr",
			"V_PlateCarrierH_CTRG",
			"V_PlateCarrierIA1_dgtl",
			"V_PlateCarrierIA2_dgtl",
			"V_PlateCarrierIAGL_dgtl",
			"V_PlateCarrierIAGL_oli",
			"V_PlateCarrierL_CTRG",
			"V_PlateCarrierSpec_blk",
			"V_PlateCarrierSpec_mtp",
			"V_PlateCarrierSpec_rgr",
			//Apex
			"V_TacChestrig_grn_F",
			"V_TacChestrig_oli_F",
			"V_TacChestrig_cbr_F",
			"V_PlateCarrier1_tna_F",
			"V_PlateCarrier2_tna_F",
			"V_PlateCarrierSpec_tna_F",
			"V_PlateCarrierGL_tna_F",
			"V_HarnessO_ghex_F",
			"V_HarnessOGL_ghex_F",
			"V_TacVest_gen_F",
			"V_PlateCarrier1_rgr_noflag_F",
			"V_PlateCarrier2_rgr_noflag_F",
			// Jets
			"V_DeckCrew_yellow_F",
			"V_DeckCrew_blue_F",
			"V_DeckCrew_green_F",
			"V_DeckCrew_red_F",
			"V_DeckCrew_white_F",
			"V_DeckCrew_brown_F",
			"V_DeckCrew_violet_F",
			"rhs_6b13_Flora",
			"rhs_6b13_Flora_6sh92",
			"rhs_6b13_EMR",
			"rhs_6b13_EMR_6sh92_radio",
			"rhs_6b13_EMR_6sh92_headset_mapcase",
			"rhs_6b13_6sh92_headset_mapcase",
			"rhs_6b23",
			"rhs_6b23_6sh116_od",
			"rhs_6b23_crew",
			"rhs_6b23_rifleman",
			"rhs_6b23_sniper",
			"rhs_6b23_digi_6sh92_headset_spetsnaz",
			"rhs_6b23_digi_engineer",
			"rhs_6b23_6sh116_flora",
			"rhs_6b23_ML_rifleman",
			"rhs_6b23_ML_6sh92_vog_headset",
			"rhs_6b43",
			"rhs_6sh46",

			"rhs_6sh92",
			"rhs_6sh92_headset",
			"rhs_6sh92_digi_vog_headset",
			"rhs_6sh92_vsr_radio",
			"rhs_vest_commander",
			"rhs_vydra_3m",
			"rhs_6sh92_digi",
			"rhsgref_chestrig",
			
			"rhsusf_iotv_ocp_Grenadier",
			"rhsusf_iotv_ucp_Grenadier",
			"rhsusf_iotv_ucp_Medic",
			"rhsusf_iotv_ocp",
			"rhsusf_iotv_ocp_Rifleman",
			"rhsusf_iotv_ucp_Rifleman",
			"rhsusf_iotv_ocp_SAW",
			"rhsusf_iotv_ocp_Squadleader",
			"rhsusf_iotv_ucp_Squadleader",
			"rhsusf_iotv_ucp",
			"rhsusf_mbav",
			"rhsusf_mbav_grenadier",
			"rhsusf_mbav_light",
			"rhsusf_mbav_rifleman",
			"rhsusf_plateframe_sapi",
			"rhsusf_plateframe_light",
			"rhsusf_plateframe_marksman",
			"rhsusf_plateframe_medic",
			"rhsusf_spc_corpsman",
			"rhsusf_spc_light",
			"rhsusf_spc_teamleader",
			"rhsusf_spc_patchless",
			"rhsusf_spcs_ucp_crewman",
			"rhsusf_spcs_ucp_grenadier",
			"rhsusf_spcs_ocp_machinegunner",
			"rhsusf_spcs_ucp_machinegunner",
			"rhsusf_spcs_ocp",
			"rhsusf_spcs_ocp_rifleman",
			"rhsusf_spcs_ucp_rifleman",
			"rhsusf_spcs_ucp",
			"rhsusf_spcs_ocp_teamleader_alt",
			"rhsusf_spcs_ucp_squadleader",
			"rhsgref_6b23_khaki_officer",
			"rhsgref_6b23_ttsko_digi_medic",
			"rhsgref_6b23_ttsko_forest_rifleman",
			"rhs_6b5_ttsko",
			"rhs_6b5_vsr",
			"rhs_6b5_medic_vsr",
			"rhsgref_otv_digi",
			
			"rhssaf_vest_md99_digital",
			"rhssaf_vest_md12_digital_desert",
			"rhssaf_vest_md98_md2camo",
			"V_EOD_blue_F",
			"V_Plain_medical_F",
			"V_Pocketed_coyote_F",
			"V_Safety_yellow_F",
			"V_Safety_blue_F",
			"V_DeckCrew_brown_F",
			"V_DeckCrew_violet_F",
			"V_DeckCrew_yellow_F"
		};
	};

	class Headgear
	{
		name = "Headgear";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\headgear_ca.paa";
		items[] =
		{
			"Exile_Headgear_SantaHat",
			"Exile_Headgear_SafetyHelmet",
			"H_Cap_blk",
			"H_Cap_blk_Raven",
			"H_Cap_blu",
			"H_Cap_brn_SPECOPS",
			"H_Cap_grn",
			"H_Cap_headphones",
			"H_Cap_khaki_specops_UK",
			"H_Cap_oli",
			"H_Cap_press",
			"H_Cap_red",
			"H_Cap_tan",
			"H_Cap_tan_specops_US",
			"H_Watchcap_blk",
			"H_Watchcap_camo",
			"H_Watchcap_khk",
			"H_Watchcap_sgg",
			"H_MilCap_blue",
			"H_MilCap_dgtl",
			"H_MilCap_mcamo",
			"H_MilCap_ocamo",
			"H_MilCap_oucamo",
			"H_MilCap_rucamo",
			"H_Bandanna_camo",
			"H_Bandanna_cbr",
			"H_Bandanna_gry",
			"H_Bandanna_khk",
			"H_Bandanna_khk_hs",
			"H_Bandanna_mcamo",
			"H_Bandanna_sgg",
			"H_Bandanna_surfer",
			"H_Booniehat_dgtl",
			"H_Booniehat_dirty",
			"H_Booniehat_grn",
			"H_Booniehat_indp",
			"H_Booniehat_khk",
			"H_Booniehat_khk_hs",
			"H_Booniehat_mcamo",
			"H_Booniehat_tan",
			"H_Hat_blue",
			"H_Hat_brown",
			"H_Hat_camo",
			"H_Hat_checker",
			"H_Hat_grey",
			"H_Hat_tan",
			"H_StrawHat",
			"H_StrawHat_dark",
			"H_Beret_02",
			"H_Beret_blk",
			"H_Beret_blk_POLICE",
			"H_Beret_brn_SF",
			"H_Beret_Colonel",
			"H_Beret_grn",
			"H_Beret_grn_SF",
			"H_Beret_ocamo",
			"H_Beret_red",
			"H_Shemag_khk",
			"H_Shemag_olive",
			"H_Shemag_olive_hs",
			"H_Shemag_tan",
			"H_ShemagOpen_khk",
			"H_ShemagOpen_tan",
			"H_TurbanO_blk",
			"H_HelmetB",
			"H_HelmetB_black",
			"H_HelmetB_camo",
			"H_HelmetB_desert",
			"H_HelmetB_grass",
			"H_HelmetB_light",
			"H_HelmetB_light_black",
			"H_HelmetB_light_desert",
			"H_HelmetB_light_grass",
			"H_HelmetB_light_sand",
			"H_HelmetB_light_snakeskin",
			"H_HelmetB_paint",
			"H_HelmetB_plain_blk",
			"H_HelmetB_sand",
			"H_HelmetB_snakeskin",
			"H_HelmetCrew_B",
			"H_HelmetCrew_I",
			"H_HelmetCrew_O",
			"H_HelmetIA",
			"H_HelmetIA_camo",
			"H_HelmetIA_net",
			"H_HelmetLeaderO_ocamo",
			"H_HelmetLeaderO_oucamo",
			"H_HelmetO_ocamo",
			"H_HelmetO_oucamo",
			"H_HelmetSpecB",
			"H_HelmetSpecB_blk",
			"H_HelmetSpecB_paint1",
			"H_HelmetSpecB_paint2",
			"H_HelmetSpecO_blk",
			"H_HelmetSpecO_ocamo",
			"H_CrewHelmetHeli_B",
			"H_CrewHelmetHeli_I",
			"H_CrewHelmetHeli_O",
			"H_HelmetCrew_I",
			"H_HelmetCrew_B",
			"H_HelmetCrew_O",
			"H_PilotHelmetHeli_B",
			"H_PilotHelmetHeli_I",
			"H_PilotHelmetHeli_O",

			//Apex
			"H_Helmet_Skate",
			"H_HelmetB_TI_tna_F",
			//"H_HelmetO_ViperSP_hex_F",
			//"H_HelmetO_ViperSP_ghex_F",
			"H_HelmetB_tna_F",
			"H_HelmetB_Enh_tna_F",
			"H_HelmetB_Light_tna_F",
			"H_HelmetSpecO_ghex_F",
			"H_HelmetLeaderO_ghex_F",
			"H_HelmetO_ghex_F",
			"H_HelmetCrew_O_ghex_F",
			"H_MilCap_tna_F",
			"H_MilCap_ghex_F",
			"H_Booniehat_tna_F",
			"H_Beret_gen_F",
			"H_MilCap_gen_F",
			"rhs_6b26_green",
			"rhs_6b26_bala_green",
			"rhs_6b26_ess_green",
			"rhs_6b26",
			"rhs_6b26_bala",
			"rhs_6b26_ess",
			"rhs_6b27m_green",
			"rhs_6b27m_green_ess",
			"rhs_6b27m_digi",
			"rhs_6b27m_digi_ess",
			"rhs_6b27m_digi_ess_bala",
			"rhs_6b27m_ess",
			"rhs_6b27m_ess_bala",
			"rhs_6b27m_ml",
			"rhs_6b28_green",
			"rhs_6b27m_ml_bala",
			"rhs_6b28_green_ess",
			"rhs_6b28",
			"rhs_6b28_flora_ess",
			"rhs_6b47_bala",
			"rhs_6b7_1m",
			"rhs_6b7_1m_emr",
			"rhs_6b7_1m_flora_ns3",
			"rhs_6b7_1m_bala2_flora",
			"rhs_6b7_1m_olive",
			"rhs_altyn_novisor",
			"rhs_altyn_novisor_bala",
			"rhs_altyn_visordown",
			"rhs_altyn_novisor_ess",
			"rhs_altyn",
			"rhs_beanie_green",
			"rhs_beret_mp2",
			"rhs_Booniehat_digi",
			"rhs_fieldcap",
			"rhs_fieldcap_helm_digi",
			"rhs_fieldcap_helm",
			"rhs_fieldcap_digi",
			"rhs_fieldcap_izlom",
			"rhs_gssh18",
			"rhs_zsh7a_mike_green_alt",
			"rhs_tsh4",
			"rhs_ssh68",
			"rhs_zsh7a",
			"rhsusf_ach_bare",
			"rhsusf_ach_bare_des_ess",
			"rhsusf_ach_bare_headset_ess",
			"rhsusf_ach_bare_wood_ess",
			"rhsusf_ach_helmet_DCU",
			"rhsusf_ach_bare_wood_headset",
			"rhsusf_ach_helmet_DCU_early_rhino",
			"rhsusf_ach_helmet_M81",
			"rhsusf_ach_helmet_ocp",
			"rhsusf_ach_helmet_ocp_alt",
			"rhsusf_ach_helmet_camo_ocp",
			"rhsusf_ach_helmet_headset_ocp_alt",
			"rhsusf_ach_helmet_headset_ess_ocp_alt",
			"rhsusf_ach_helmet_ucp",
			"rhsusf_ach_helmet_ucp_alt",
			"rhsusf_ach_helmet_ESS_ucp",
			"rhsusf_ach_helmet_headset_ess_ucp",
			"rhsusf_cvc_green_helmet",
			"rhsusf_cvc_green_alt_helmet",
			"rhsusf_cvc_helmet",
			"rhsusf_cvc_green_ess",
			"rhsusf_cvc_alt_helmet",
			"rhs_booniehat2_marpatd",
			"rhs_Booniehat_m81",
			"rhs_Booniehat_ocp",
			"rhsusf_bowman_cap",
			"rhsusf_Bowman",
			"rhs_xmas_antlers",
			"rhsusf_opscore_aor1",
			"rhsusf_opscore_aor1_pelt",
			"rhsusf_opscore_aor2",
			"rhsusf_opscore_aor2_pelt_nsw",
			"rhsusf_opscore_bk_pelt",
			"rhsusf_opscore_coy_cover_pelt",
			"rhsusf_opscore_fg",
			"rhsusf_opscore_fg_pelt",
			"rhsusf_opscore_fg_pelt_nsw",
			"rhsusf_opscore_mc_cover",
			"rhsusf_opscore_mc_cover_pelt_nsw",
			"rhsusf_opscore_mc_pelt",
			"rhsusf_opscore_paint_pelt",
			"rhsusf_opscore_paint",
			"rhsusf_opscore_rg_cover_pelt",
			"rhsusf_opscore_ut_pelt_cam",
			"rhsusf_opscore_mar_ut",
			"rhsusf_hgu56p_black",
			"rhsusf_hgu56p_visor_mask_black",
			"rhsusf_hgu56p_visor_mask_black_skull",
			"rhsusf_hgu56p_visor_mask_green_mo",
			"rhsusf_hgu56p_mask_skull",
			"rhsusf_hgu56p_visor_mask_skull",
			"rhsusf_hgu56p_visor",
			"rhsusf_hgu56p_visor_mask_pink",
			"rhsusf_hgu56p_visor_mask_saf",
			"rhsusf_hgu56p_pink",
			"rhsusf_hgu56p_saf",
			"rhsusf_hgu56p_visor_mask_smiley",
			"rhsusf_hgu56p_tan",
			"rhsusf_hgu56p_usa",
			"rhsusf_hgu56p_visor_usa",
			"rhsusf_hgu56p_visor_white",
			"RHS_jetpilot_usaf",
			"rhsusf_lwh_helmet_marpatd",
			"rhsusf_lwh_helmet_marpatd_ess",
			"rhsusf_lwh_helmet_marpatd_headset",
			"rhsusf_lwh_helmet_marpatwd",
			"rhsusf_lwh_helmet_marpatwd_blk_ess",
			"rhsusf_lwh_helmet_marpatwd_headset_blk",
			"rhsusf_mich_bare",
			"rhsusf_mich_bare_norotos_arc",
			"rhsusf_mich_bare_norotos_alt_headset",
			"rhsusf_mich_bare_norotos_arc_headset",
			"rhsusf_mich_bare_semi",
			"rhsusf_mich_bare_norotos_headset",
			"rhsusf_mich_bare_norotos_arc_alt_semi",
			"rhsusf_mich_bare_norotos_arc_semi_headset",
			"rhsusf_mich_bare_tan",
			"rhsusf_mich_bare_norotos_alt_tan",
			"rhsusf_mich_bare_norotos_arc_tan",
			"rhsusf_mich_bare_norotos_arc_alt_tan",
			"rhsusf_mich_helmet_marpatd_headset",
			"rhsusf_mich_helmet_marpatd_norotos_arc",
			"rhsusf_mich_helmet_marpatwd_alt",
			"rhsusf_mich_helmet_marpatwd_norotos_arc",
			"rhsusf_patrolcap_ucp",
			"rhsusf_protech_helmet",
			"rhsusf_protech_helmet_rhino_ess",
			"rhsgref_un_beret",
			"rhsgref_fieldcap_ttsko_forest",
			"rhsgref_6b27m_ttsko_digi",
			"rhsgref_helmet_M1_painted_alt01",
			"rhsgref_helmet_M1_liner",
			"rhsgref_helmet_m1940",
			"rhsgref_helmet_m1940_camo01",
			"rhsgref_helmet_m1940_winter_alt1",
			"rhsgref_helmet_m1942_heergreycover",
			"rhsgref_helmet_m1942_heermarshcover",
			"rhsgref_helmet_pasgt_3color_desert",
			"rhsgref_M56",
			"rhsgref_helmet_pasgt_erdl",
			"rhsgref_helmet_pasgt_un",
			"rhsgref_ssh68_ttsko_forest",
			"rhsgref_helmet_pasgt_press",
			"rhsgref_ssh68_un",
			"rhssaf_bandana_digital",
			"rhssaf_beret_black",
			"rhssaf_beret_blue_un",
			"rhssaf_helmet_m59_85_nocamo",
			"rhssaf_helmet_m97_black_nocamo",
			"rhssaf_helmet_m97_black_nocamo_black_ess_bare",
			"rhssaf_helmet_m97_nostrap_blue_tan_ess_bare",
			"rhssaf_helmet_m97_nostrap_blue",
			"rhssaf_helmet_m97_oakleaf",
			"rhssaf_helmet_m97_oakleaf_black_ess",
			"rhssaf_helmet_m97_olive_nocamo",
			"rhssaf_helmet_m97_woodland",
			"rhssaf_helmet_m97_olive_nocamo_black_ess_bare",
			"rhssaf_helmet_m97_woodland_black_ess_bare",
			"rhssaf_helmet_m97_veil_woodland"
		};
	};

	class Glasses
	{
		name = "Glasses";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\Goggles_ca.paa";
		items[] =
		{
			"G_Aviator",
			"G_Balaclava_blk",
			"G_Bandanna_aviator",
			"G_Bandanna_beast",
			"G_Bandanna_blk",
			"G_Bandanna_khk",
			"G_Bandanna_oli",
			"G_Bandanna_shades",
			"G_Bandanna_sport",
			"G_Bandanna_tan",
			"G_Combat",
			"G_Lady_Blue",
			"G_Lowprofile",
			"G_Shades_Black",
			"G_Shades_Blue",
			"G_Shades_Green",
			"G_Shades_Red",
			"G_Spectacles",
			"G_Sport_Red",
			"G_Sport_Blackyellow",
			"G_Sport_BlackWhite",
			"G_Sport_Checkered",
			"G_Sport_Blackred",
			"G_Sport_Greenblack",
			"G_Squares_Tinted",
			"G_Squares",
			"G_Tactical_Clear",
			"G_Tactical_Black",
			"G_Spectacles_Tinted",
			"G_Goggles_VR",
			"G_Combat_Goggles_tna_F",
			"G_Balaclava_TI_blk_F",
			"G_Balaclava_TI_G_blk_F",
			"G_Balaclava_TI_tna_F",
			"G_Balaclava_TI_tna_F",
			"G_Balaclava_TI_G_tna_F",
			"G_Blindfold_01_black_F",
			"G_Blindfold_01_white_F",
			"rhs_balaclava",
			"rhs_balaclava1_olive",
			"rhs_scarf",
			"rhs_googles_black",
			"rhs_googles_yellow",
			"rhs_googles_orange",
			"rhs_googles_clear",
			"rhs_ess_black",
			"rhsusf_shemagh_grn",
			"rhsusf_shemagh2_grn",
			"rhsusf_shemagh_od",
			"rhsusf_shemagh2_od",
			"rhsusf_shemagh_tan",
			"rhsusf_shemagh2_tan",
			"rhsusf_shemagh_white",
			"rhsusf_shemagh2_white",
			"rhsusf_shemagh_gogg_grn",
			"rhsusf_shemagh2_gogg_grn",
			"rhsusf_shemagh_gogg_od",
			"rhsusf_shemagh2_gogg_od",
			"rhsusf_shemagh2_gogg_tan",
			"rhsusf_shemagh_gogg_tan",
			"rhsusf_shemagh_gogg_white",
			"rhsusf_shemagh2_gogg_white",
			"rhsusf_oakley_goggles_blk",
			"rhsusf_oakley_goggles_clr",
			"rhsusf_oakley_goggles_ylw",
			"rhssaf_veil_Green",
			"G_Respirator_blue_F",
			"G_Respirator_white_F",
			"G_Respirator_yellow_F",
			"G_EyeProtectors_F",
			"G_EyeProtectors_Earpiece_F",
			"G_WirelessEarpiece_F"
		};
	};

	class PointerAttachments
	{
		name = "Attachments";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"rhs_acc_2dpzenit_ris",
			"rhsusf_acc_anpeq15side",
			"rhsusf_acc_anpeq15side_bk",
			"rhsusf_acc_anpeq15a",
			"rhsusf_acc_anpeq16a",
			"rhsusf_acc_anpeq16a_light",
			"acc_pointer_ir",
			"rhsusf_acc_m952v",
			"rhs_acc_perst1ik_ris",
			"rhs_acc_perst3",
			"acc_flashlight",
			"rhsusf_acc_wmx",
			"rhsusf_acc_wmx_bk",
			"acc_flashlight_pistol",
			"rhs_acc_2dpzenit",
			"rhs_acc_perst1ik"
		};
	};

	class BipodAttachments
	{
		name = "Bipod Attachments";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itembipod_ca.paa";
		items[] =
		{
			"rhsusf_acc_grip2",
			"rhsusf_acc_grip2_tan",
			"rhsusf_acc_grip2_wd",
			"bipod_02_f_arid",
			"bipod_03_f_blk",
			"bipod_02_f_blk",
			"bipod_01_f_blk",
			"bipod_02_f_hex",
			"bipod_02_f_lush",
			"bipod_01_f_khk",
			"bipod_01_f_mtp",
			"bipod_03_f_oli",
			"bipod_01_f_snd",
			"bipod_02_f_tan",
			"rhs_acc_grip_ffg2",
			"rhsusf_acc_grip1",
			"rhsusf_acc_harris_bipod",
			"rhs_acc_harris_swivel",
			"rhsusf_acc_kac_grip",
			"rhs_acc_grip_rk2",
			"rhs_acc_grip_rk6",
			"rhsusf_acc_rvg_blk",
			"rhsusf_acc_rvg_de",
			"rhsusf_acc_tacsac_blk",
			"rhsusf_acc_tacsac_blue",
			"rhsusf_acc_tacsac_tan",
			"rhsusf_acc_tdstubby_blk",
			"rhsusf_acc_tdstubby_tan",
			"rhsusf_acc_grip3",
			"rhsusf_acc_grip3_tan"
		};
	};

	class MuzzleAttachments
	{
		name = "Suppressor Attachments";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemmuzzle_ca.paa";
		items[] =
		{
			"muzzle_snds_570",
			"rhsgref_sdn6_suppressor",
			"rhs_acc_dtk2",
			"rhs_acc_tgpv",
			"rhs_acc_tgpv2",
			"muzzle_snds_58_blk_F",
			"muzzle_snds_58_wdm_F",
			"muzzle_snds_65_TI_blk_F",
			"muzzle_snds_65_TI_ghex_F",
			"muzzle_snds_65_TI_hex_F",
			"muzzle_snds_B_khk_F",
			"muzzle_snds_B_snd_F",
			"muzzle_snds_H_MG_blk_F",
			"muzzle_snds_H_MG_khk_F",
			"muzzle_snds_H_khk_F",
			"muzzle_snds_H_snd_F",
			"muzzle_snds_m_khk_F",
			"muzzle_snds_m_snd_F",
			"muzzle_snds_338_black",
			"muzzle_snds_338_green",
			"muzzle_snds_338_sand",
			"muzzle_snds_93mmg",
			"muzzle_snds_93mmg_tan",
			"muzzle_snds_B",
			"muzzle_snds_H",
			"muzzle_snds_H_MG",
			"muzzle_snds_H_SW",
			"muzzle_snds_L",
			"muzzle_snds_M",
			"muzzle_snds_acp",
			
			"rhsusf_acc_SF3P556",
			"rhsusf_acc_SFMB556",
			"rhsusf_acc_nt4_tan",
			"rhsusf_acc_rotex5_grey",
			"rhsusf_acc_rotex5_tan",
			"rhsusf_acc_SR25S",
			"rhsusf_acc_M2010S",
			"rhs_acc_ak5",
			"rhs_acc_dtk",
			"rhs_acc_dtk1",
			"rhs_acc_dtk3",
			"rhs_acc_dtk4screws",
			"rhs_acc_dtk4long",
			"rhs_acc_dtk4short",
			"rhs_acc_tgpa",
			"rhs_acc_dtk1l",
			"rhs_acc_pbs1",
			"rhsusf_acc_omega9k",
			"rhs_acc_uuk",
			"rhsusf_acc_rotex_mp7",
			"rhsusf_acc_rotex_mp7_desert",
			"rhsusf_acc_rotex_mp7_winter",
			"rhsusf_acc_rotex_mp7_aor1"
		};
	};

	class UAVs
	{
		name = "Unmanned Aerial Vehicles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\gps_ca.paa";
		items[] =
		{
			"I_UAV_01_backpack_F",
			"I_UavTerminal"
		};
	};

	class StaticMGs
	{
		name = "Static Machine Guns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"O_HMG_01_support_F",
			"O_HMG_01_weapon_F"
		};
	};

	class OpticAttachments
	{
		name = "Scopes";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemoptic_ca.paa";
		items[] =
		{
			"rhs_acc_rakurspm",
			"rhs_acc_1p87",
			"rhsusf_acc_anpas13gv1",
			"rhsusf_acc_acog2_usmc",
			"rhsusf_acc_acog3_usmc",
			"rhsusf_acc_acog_usmc",
			"rhsusf_acc_anpvs27",
			"optic_arco_ak_arid_f",
			"optic_arco_lush_f",
			"optic_arco_arid_f",
			"optic_arco_ak_blk_f",
			"optic_arco_ak_lush_f",
			"optic_yorris",
			"optic_dms",
			"optic_dms_ghex_f",
			"optic_aco_grn",
			"optic_aco",
			"optic_aco_grn_smg",
			"optic_aco_smg",
			"rhs_acc_dh520x56",
			"optic_dms_weathered_f",
			"optic_dms_weathered_kir_f",
			"rhs_acc_ekp8_18",
			"optic_arco_blk_f",
			"optic_arco_ghex_f",
			"optic_arco",
			"optic_holosight_blk_f",
			"optic_holosight_khk_f",
			"optic_holosight",
			"optic_holosight_smg_blk_f",
			"optic_holosight_smg_khk_f",
			"optic_holosight_smg",
			"rhsusf_acc_eotech",
			"rhsusf_acc_g33_t1",
			"rhsusf_acc_g33_xps3",
			"rhsusf_acc_g33_xps3_tan",
			"optic_mrco",
			"optic_khs_blk",
			"optic_khs_hex",
			"optic_khs_old",
			"optic_khs_tan",
			"optic_hamr",
			"optic_hamr_khk_f",
			"rhsusf_acc_elcan",
			"rhsusf_acc_elcan_ard",
			"rhsusf_acc_acog",
			"rhsusf_acc_acog2",
			"rhsusf_acc_acog3",
			"rhsusf_acc_acog_anpvs27",
			"rhsusf_acc_m2a1",
			"rhsusf_acc_eotech_552",
			"rhsusf_acc_eotech_552_d",
			"rhsusf_acc_eotech_552_wd",
			"rhsusf_acc_compm4",
			"rhsusf_acc_m8541",
			"rhsusf_acc_m8541_low",
			"rhsusf_acc_m8541_low_d",
			"rhsusf_acc_m8541_low_wd",
			"rhsusf_acc_m8541_mrds",
			"rhsusf_acc_premier_low",
			"rhsusf_acc_premier",
			"rhsusf_acc_premier_mrds",
			"rhsusf_acc_leupoldmk4",
			"rhsusf_acc_leupoldmk4_2",
			"rhsusf_acc_leupoldmk4_d",
			"rhsusf_acc_leupoldmk4_wd",
			"rhsusf_acc_leupoldmk4_2_d",
			"rhsusf_acc_leupoldmk4_2_mrds",
			"optic_holosight_arid_f",
			"optic_holosight_lush_f",
			"optic_sos",
			"optic_sos_khk_f",
			"rhsusf_acc_mrds",
			"rhsusf_acc_mrds_c",
			"optic_lrps",
			"optic_lrps_ghex_f",
			"optic_lrps_tna_f",
			"optic_nightstalker",
			"optic_nvs",
			"rhs_acc_okp7_picatinny",
			"rhsusf_acc_rx01_nofilter",
			"rhsusf_acc_rm05",
			"rhsgref_acc_rx01_nofilter_camo",
			"rhsgref_acc_rx01_camo",
			"rhsusf_acc_rx01",
			"rhsusf_acc_rx01_nofilter_tan",
			"optic_erco_blk_f",
			"rhsusf_acc_rx01_tan",
			"optic_erco_khk_f",
			"optic_erco_snd_f",
			"rhsusf_acc_su230",
			"rhsusf_acc_su230_c",
			"rhsusf_acc_su230_mrds",
			"rhsusf_acc_su230a",
			"rhsusf_acc_su230_mrds_c",
			"rhsusf_acc_su230a_c",
			"rhsusf_acc_su230a_mrds",
			"rhsusf_acc_su230a_mrds_c",
			"rhsusf_acc_t1_high",
			"rhsusf_acc_acog_mdo",
			"rhsusf_acc_t1_low",
			"rhsusf_acc_acog_rmr",
			"rhsusf_acc_acog_d",
			"rhsusf_acc_acog_wd",
			"optic_ams",
			"optic_ams_khk",
			"optic_ams_snd",
			"rhs_acc_1p29",
			"rhs_acc_1p63",
			"rhs_acc_1p78",
			"rhs_acc_1pn93_1",
			"rhs_acc_1pn93_2",
			"rhs_acc_ekp1",
			"rhs_acc_ekp8_02",
			"rhsusf_acc_mrds_fwd",
			"rhsusf_acc_mrds_fwd_c",
			"rhs_acc_nita",
			"rhs_acc_okp7_dovetail",
			"rhs_acc_pgo7v2",
			"rhs_acc_pgo7v",
			"rhs_acc_pgo7v3",
			"rhs_acc_pkas",
			"rhs_acc_pso1m2",
			"rhs_acc_pso1m21",
			"rhsusf_acc_rm05_fwd",
			"rhsusf_acc_t1_low_fwd",
			"optic_tws",
			"optic_tws_mg",
			"optic_mrd",
			"optic_mrd_black"
		};
	};

	class Hardware
	{
		name = "Hardware";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{

			"Exile_Item_DuctTape",
			"Exile_Item_ExtensionCord",
			"Exile_Item_FuelCanisterEmpty",
			"Exile_Item_JunkMetal",
			"Exile_Item_LightBulb",
			"Exile_Item_MetalBoard",
			"Exile_Item_MetalPole",
			"Exile_Item_SafeKit",
			"Exile_Item_CamoTentKit",
			"Exile_Item_CodeLock",
			"Exile_Item_MetalScrews"

			/*
			--Not for Sale--
			"Exile_Item_MetalWire",
			"Exile_Item_Laptop",
			"Exile_Item_BaseCameraKit",
			"Exile_Item_MetalHedgehogKit",
			"Exile_Item_Cement",
			"Exile_Item_Sand",
			"Exile_Item_MobilePhone",
			--Unused--
			"Exile_Item_SprayCan_Black",
			"Exile_Item_SprayCan_Red",
			"Exile_Item_SprayCan_Green",
			"Exile_Item_SprayCan_White",
			"Exile_Item_SprayCan_Blue",
			"Exile_Item_CordlessScrewdriver",
			"Exile_Item_FireExtinguisher",
			"Exile_Item_OilCanister",
			"Exile_Item_Hammer",
			"Exile_Item_Carwheel",
			"Exile_Item_SleepingMat",
			"Exile_Item_Defibrillator",
			"Exile_Item_Wrench",
			"Exile_Item_Rope"
		*/
		};
	};

	class Food
	{
		name = "Fast Food";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Item_EMRE",
			"Exile_Item_GloriousKnakworst",
			"Exile_Item_Surstromming",
			"Exile_Item_SausageGravy",
			"Exile_Item_Catfood",
			"Exile_Item_ChristmasTinner",
			"Exile_Item_BBQSandwich",
			"Exile_Item_MacasCheese",
			"Exile_Item_Dogfood",
			"Exile_Item_BeefParts",
			"Exile_Item_Cheathas",
			"Exile_Item_Noodles",
			"Exile_Item_SeedAstics",
			"Exile_Item_Raisins",
			"Exile_Item_Moobar",
			"Exile_Item_InstantCoffee"
			
			//Hunted Animals
			//Note: Adding these to the trader will defeat the purpose of hunting!
			/*
			"Exile_Item_SheepSteak_Cooked",
			"Exile_Item_AlsatianSteak_Cooked",
			"Exile_Item_CatSharkFilet_Cooked",
			"Exile_Item_FinSteak_Cooked",
			"Exile_Item_GoatSteak_Cooked",
			"Exile_Item_TurtleFilet_Cooked",
			"Exile_Item_TunaFilet_Cooked",
			"Exile_Item_RabbitSteak_Cooked",
			"Exile_Item_ChickenFilet_Cooked",
			"Exile_Item_RoosterFilet_Cooked",
			"Exile_Item_MulletFilet_Cooked",
			"Exile_Item_SalemaFilet_Cooked",
			"Exile_Item_MackerelFilet_Cooked",
			"Exile_Item_OrnateFilet_Cooked",
			"Exile_Item_SnakeFilet_Cooked",
			"Exile_Item_CatSharkFilet_Raw",
			"Exile_Item_TunaFilet_Raw",
			"Exile_Item_AlsatianSteak_Raw",
			"Exile_Item_TurtleFilet_Raw",
			"Exile_Item_SheepSteak_Raw",
			"Exile_Item_FinSteak_Raw",
			"Exile_Item_GoatSteak_Raw",
			"Exile_Item_ChickenFilet_Raw",
			"Exile_Item_RoosterFilet_Raw",
			"Exile_Item_MackerelFilet_Raw",
			"Exile_Item_MulletFilet_Raw",
			"Exile_Item_OrnateFilet_Raw",
			"Exile_Item_RabbitSteak_Raw",
			"Exile_Item_SalemaFilet_Raw",
			"Exile_Item_SnakeFilet_Raw"
			*/
		};
	};
	
	class NonVeganFood
	{
		name = "Non-Vegan Food";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Item_CatSharkFilet_Raw",
			"Exile_Item_TunaFilet_Raw",
			"Exile_Item_AlsatianSteak_Raw",
			"Exile_Item_TurtleFilet_Raw",
			"Exile_Item_SheepSteak_Raw",
			"Exile_Item_FinSteak_Raw",
			"Exile_Item_GoatSteak_Raw",
			"Exile_Item_ChickenFilet_Raw",
			"Exile_Item_RoosterFilet_Raw",
			"Exile_Item_MackerelFilet_Raw",
			"Exile_Item_MulletFilet_Raw",
			"Exile_Item_OrnateFilet_Raw",
			"Exile_Item_RabbitSteak_Raw",
			"Exile_Item_SalemaFilet_Raw",
			"Exile_Item_SnakeFilet_Raw"
		};
	};

	class Drinks
	{
		name = "Drinks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Item_PlasticBottleCoffee",
			"Exile_Item_PowerDrink",
			"Exile_Item_PlasticBottleFreshWater",
			"Exile_Item_Beer",
			"Exile_Item_EnergyDrink",
			"Exile_Item_ChocolateMilk",
			"Exile_Item_MountainDupe",
			"Exile_Item_PlasticBottleEmpty"
		};
	};

	class Tools
	{
		name = "Tools";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Item_Matches",
			"Exile_Item_CookingPot",
			"Exile_Item_CanOpener",
			"Exile_Item_Handsaw",
			"Exile_Item_Pliers",
			"Exile_Item_Grinder",
			"Exile_Item_Foolbox",
			"Exile_Item_Knife",
			/*
			"Exile_Item_CordlessScrewdriver",
			"Exile_Item_FireExtinguisher",
			"Exile_Item_Hammer",
			"Exile_Item_OilCanister",
			"Exile_Item_Screwdriver",
			"Exile_Item_Shovel",
			"Exile_Item_Wrench",
			"Exile_Item_SleepingMat",
			"Exile_Item_ToiletPaper",
			"Exile_Item_ZipTie",
			"Exile_Item_BurlapSack",
			"Exile_Item_Bullets_556",
			"Exile_Item_Bullets_762",
			"Exile_Item_WeaponParts",
			*/

			"Binocular",
			"Rangefinder",
			/*
			"Laserdesignator",
			"Laserdesignator_02",
			"Laserdesignator_03",
			*/
			
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"Exile_Item_XM8"			
		};
	};

	class FirstAid
	{
		name = "FirstAid";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
			"Exile_Item_InstaDoc",
			"Exile_Item_Bandage",
			"Exile_Item_Vishpirin",
			"Exile_Item_Heatpack",
			"Exile_Item_Defibrillator"
		};
	};

	class Navigation
	{
		name = "Special";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Headgear_GasMask",
			"Binocular",
			"Exile_Item_MobilePhone",
			"Exile_Item_XM8",
			"ItemCompass",
			"ItemGPS",
			"ItemMap",
			"ItemRadio",
			"ItemWatch",
			"Laserdesignator",
			"Laserdesignator_02",
			"Laserdesignator_03",
			"NVGoggles",
			"NVGoggles_INDEP",
			"NVGoggles_OPFOR",
			"Rangefinder",
			"H_HelmetO_ViperSP_ghex_F",
			"H_HelmetO_ViperSP_hex_F",
			"Laserdesignator_01_khk_F",
			"Laserdesignator_02_ghex_F",
			"NVGogglesB_blk_F",
			"NVGogglesB_grn_F",
			"NVGogglesB_gry_F"
		};
	};

	class Backpacks
	{
		name = "Backpacks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
		items[] =
		{
			"B_AssaultPack_blk",
			"B_AssaultPack_cbr",
			"B_AssaultPack_dgtl",
			"B_AssaultPack_rgr",
			"B_AssaultPack_ocamo",
			"B_AssaultPack_khk",
			"B_AssaultPack_mcamo",
			"B_AssaultPack_sgg",
			"B_AssaultPack_tna_F",
			"B_Carryall_cbr",
			"B_Carryall_ocamo",
			"B_Carryall_khk",
			"B_Carryall_mcamo",
			"B_Carryall_oucamo",
			"B_Carryall_oli",
			"B_Carryall_ghex_F",
			"B_FieldPack_blk",
			"B_FieldPack_ghex_F",
			"B_FieldPack_cbr",
			"B_FieldPack_ocamo",
			"B_FieldPack_khk",
			"B_FieldPack_oli",
			"B_FieldPack_oucamo",
			"B_Kitbag_cbr",
			"B_Kitbag_rgr",
			"B_Kitbag_mcamo",
			"B_Kitbag_sgg",
			"B_Kitbag_tan",
			"B_Parachute",
			"B_TacticalPack_blk",
			"B_TacticalPack_rgr",
			"B_TacticalPack_ocamo",
			"B_TacticalPack_mcamo",
			"B_TacticalPack_oli",
			"B_Bergen_dgtl_F",
			"B_Bergen_hex_F",
			"B_Bergen_mcamo_F",
			"B_Bergen_tna_F",
			"B_ViperHarness_blk_F",
			"B_ViperHarness_ghex_F",
			"B_ViperHarness_hex_F",
			"B_ViperHarness_khk_F",
			"B_ViperHarness_oli_F",
			"B_ViperLightHarness_blk_F",
			"B_ViperLightHarness_ghex_F",
			"B_ViperLightHarness_hex_F",
			"B_ViperLightHarness_khk_F",
			"B_ViperLightHarness_oli_F",
			"B_RadioBag_01_black_F",
			"B_SCBA_01_F",
			"B_LegStrapBag_black_F",
			"B_LegStrapBag_coyote_F",
			"B_LegStrapBag_olive_F",
			"B_Messenger_Black_F",
			"B_Messenger_Coyote_F",
			"B_Messenger_Olive_F",
			"B_Messenger_Gray_F",
			"B_Messenger_IDAP_F",
			"rhs_rpg_empty",
			"rhs_sidor",
			"rhs_medic_bag",
			"rhsusf_assault_eagleaiii_coy",
			"rhs_assault_umbts_engineer_empty",
			"rhsusf_eject_Parachute_backpack",
			"rhsgref_hidf_alicepack"
		};
	};

	class Ammunition
	{
		name = "Ammunition";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\CargoMag_ca.paa";
		items[] =
		{
			"Exile_Magazine_5Rnd_22LR",
			"Exile_Magazine_10Rnd_303",
			"Exile_Magazine_10Rnd_338_Bullet_Cam_Mag",
			"10Rnd_338_Mag",
			"130Rnd_338_Mag",
			"Exile_Magazine_7Rnd_408_Bullet_Cam_Mag",
			"7Rnd_408_Mag",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01_Tracer_Green",
			"9Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"30Rnd_45ACP_Mag_SMG_01_Tracer_Red",
			"30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",
			"6Rnd_45ACP_Cylinder",
			"Exile_Magazine_7Rnd_45ACP",
			"10Rnd_50BW_Mag_F",
			"rhs_mag_100Rnd_556x45_M855_cmag",
			"rhs_mag_100Rnd_556x45_M855_cmag_mixed",
			"rhs_mag_100Rnd_556x45_M855A1_cmag",
			"rhs_mag_100Rnd_556x45_M855A1_cmag_mixed",
			"rhs_mag_100Rnd_556x45_Mk262_cmag",
			"rhs_mag_100Rnd_556x45_Mk318_cmag",
			"rhssaf_100rnd_556x45_EPR_G36",
			"rhsusf_100Rnd_762x51_m61_ap",
			"rhsusf_100Rnd_762x51_m62_tracer",
			"rhsusf_100Rnd_762x51",
			"rhsusf_100Rnd_762x51_m80a1epr",
			"rhsusf_100Rnd_762x51_m82_blank",
			"rhsusf_100Rnd_556x45_M200_soft_pouch_ucp",
			"rhsusf_100Rnd_556x45_M200_soft_pouch_coyote",
			"rhsusf_100Rnd_556x45_M200_soft_pouch",
			"rhsusf_100Rnd_556x45_M855_soft_pouch_coyote",
			"rhsusf_100Rnd_556x45_M855_soft_pouch_ucp",
			"rhsusf_100Rnd_556x45_M855_soft_pouch",
			"rhsusf_100Rnd_556x45_M855_mixed_soft_pouch_ucp",
			"rhsusf_100Rnd_556x45_M855_mixed_soft_pouch_coyote",
			"rhsusf_100Rnd_556x45_M855_mixed_soft_pouch",
			"rhsusf_100Rnd_556x45_soft_pouch_coyote",
			"rhsusf_100Rnd_556x45_soft_pouch",
			"rhsusf_100Rnd_556x45_soft_pouch_ucp",
			"rhsusf_100Rnd_556x45_mixed_soft_pouch",
			"rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",
			"rhsusf_100Rnd_556x45_mixed_soft_pouch_ucp",
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR_7BZ3",
			"rhs_100Rnd_762x54mmR_7N13",
			"rhs_100Rnd_762x54mmR_7N26",
			"rhs_100Rnd_762x54mmR_green",
			"rhsusf_10Rnd_762x51_m118_special_Mag",
			"rhsusf_10Rnd_762x51_m62_Mag",
			"rhsusf_10Rnd_762x51_m993_Mag",
			"rhs_10Rnd_762x39mm",
			"rhs_10Rnd_762x39mm_89",
			"rhs_10Rnd_762x39mm_tracer",
			"rhs_10Rnd_762x39mm_U",
			"rhs_10rnd_9x39mm_SP5",
			"rhs_10rnd_9x39mm_SP6",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_mk211",
			"rhssaf_10Rnd_792x57_m76_tracer",
			"rhsgref_10Rnd_792x57_m76",
			"rhsgref_10rnd_765x17_vz61",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N14",
			"10Rnd_127x99_m107",
			"10Rnd_762x54_SVD",
			"2Rnd_12Gauge_Pellets",
			"2Rnd_12Gauge_Slug",
			"6Rnd_12Gauge_Pellets",
			"6Rnd_12Gauge_Slug",
			"Exile_Magazine_10Rnd_127x99_m107_Bullet_Cam_Mag",
			"Exile_Magazine_10Rnd_127x99_m107",
			"10Rnd_127x54_Mag",
			"Exile_Magazine_5Rnd_127x108_Bullet_Cam_Mag",
			"Exile_Magazine_5Rnd_127x108_KSVK_Bullet_Cam_Mag",
			"Exile_Magazine_5Rnd_127x108_APDS_Bullet_Cam_Mag",
			"Exile_Magazine_5Rnd_127x108_APDS_KSVK_Bullet_Cam_Mag",
			"5Rnd_127x108_APDS_Mag",
			"Exile_Magazine_5Rnd_127x108_KSVK",
			"5Rnd_127x108_Mag",
			"rhs_mag_9x18_12_57N181S",
			"rhsusf_mag_15Rnd_9x19_FMJ",
			"rhsusf_mag_15Rnd_9x19_JHP",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_JHP",
			"rhs_mag_9x19_17",
			"rhs_18rnd_9x21mm_7BT3",
			"rhs_18rnd_9x21mm_7N28",
			"rhs_18rnd_9x21mm_7N29",
			"rhsgref_1Rnd_00Buck",
			"rhsgref_1Rnd_Slug",
			"rhsusf_200rnd_556x45_M855_box",
			"rhsusf_200rnd_556x45_M855_mixed_box",
			"rhsusf_200Rnd_556x45_box",
			"rhsusf_200rnd_556x45_mixed_box",
			"rhsusf_200Rnd_556x45_M855_soft_pouch_ucp",
			"rhsusf_200Rnd_556x45_M855_soft_pouch_coyote",
			"rhsusf_200Rnd_556x45_M855_soft_pouch",
			"rhsusf_200Rnd_556x45_M855_mixed_soft_pouch",
			"rhsusf_200Rnd_556x45_M855_mixed_soft_pouch_ucp",
			"rhsusf_200Rnd_556x45_M855_mixed_soft_pouch_coyote",
			"rhsusf_200Rnd_556x45_soft_pouch_ucp",
			"rhsusf_200Rnd_556x45_soft_pouch_coyote",
			"rhsusf_200Rnd_556x45_soft_pouch",
			"rhsusf_200Rnd_556x45_mixed_soft_pouch_ucp",
			"rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",
			"rhsusf_200Rnd_556x45_mixed_soft_pouch",
			"rhsgref_20rnd_1143x23_M1T_SMG",
			"rhsgref_20rnd_1143x23_M1911B_SMG",
			"rhs_20rnd_9x39mm_SP5",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_mag_20Rnd_762x51_m61_fnfal",
			"rhs_mag_20Rnd_762x51_m62_fnfal",
			"rhs_mag_20Rnd_762x51_m80_fnfal",
			"rhs_mag_20Rnd_762x51_m80a1_fnfal",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhsusf_20Rnd_762x51_m993_Mag",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n31_20",
			"rhs_mag_20Rnd_SCAR_762x51_m118_special",
			"rhs_mag_20Rnd_SCAR_762x51_m118_special_bk",
			"rhs_mag_20Rnd_SCAR_762x51_m61_ap",
			"rhs_mag_20Rnd_SCAR_762x51_m61_ap_bk",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer_bk",
			"rhs_mag_20Rnd_SCAR_762x51_m80_ball",
			"rhs_mag_20Rnd_SCAR_762x51_m80_ball_bk",
			"rhs_mag_20Rnd_SCAR_762x51_m80a1_epr",
			"rhs_mag_20Rnd_SCAR_762x51_m80a1_epr_bk",
			"rhs_mag_20Rnd_SCAR_762x51_mk316_special",
			"rhs_mag_20Rnd_SCAR_762x51_mk316_special_bk",
			"rhsgref_20rnd_765x17_vz61",
			"rhsusf_20Rnd_762x51_SR25_m118_special_Mag",
			"rhsusf_20Rnd_762x51_SR25_m62_Mag",
			"rhsusf_20Rnd_762x51_SR25_m993_Mag",
			"rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",
			"rhs_mag_20Rnd_556x45_M193_2MAG_Stanag",
			"rhs_mag_20Rnd_556x45_M196_2MAG_Stanag_Tracer_Red",
			"rhs_mag_20Rnd_556x45_M193_Stanag",
			"rhs_mag_20Rnd_556x45_M196_Stanag_Tracer_Red",
			"rhs_mag_20Rnd_556x45_M200_Stanag",
			"rhs_mag_20Rnd_556x45_M855_Stanag",
			"rhs_mag_20Rnd_556x45_M855A1_Stanag",
			"rhs_mag_20Rnd_556x45_Mk262_Stanag",
			"rhsgref_24rnd_75x55_Stgw57",
			"rhssaf_250Rnd_762x54R",
			"rhsgref_25Rnd_792x33_SmE_StG",
			"rhsgref_296Rnd_792x57_SmE_belt",
			"rhsgref_296Rnd_792x57_SmE_notracers_belt",
			"rhsgref_296Rnd_792x57_SmK_belt",
			"rhsgref_296Rnd_792x57_SmK_alltracers_belt",
			"rhsgref_30rnd_1143x23_M1T_SMG",
			"rhsgref_30rnd_1143x23_M1T_2mag_SMG",
			"rhsgref_30rnd_1143x23_M1911B_SMG",
			"rhsgref_30rnd_1143x23_M1911B_2mag_SMG",
			"rhsgref_30Rnd_792x33_SmE_StG",
			"rhs_30Rnd_762x39mm_polymer",
			"rhs_30Rnd_762x39mm_polymer_89",
			"rhs_30Rnd_762x39mm_polymer_tracer",
			"rhs_30Rnd_762x39mm_polymer_U",
			"rhs_30Rnd_545x39_7N10_2mag_AK",
			"rhs_30Rnd_545x39_7N10_2mag_camo_AK",
			"rhs_30Rnd_545x39_7N10_2mag_desert_AK",
			"rhs_30Rnd_545x39_7N10_2mag_plum_AK",
			"rhs_30Rnd_545x39_AK_green",
			"rhs_30Rnd_545x39_7N6_AK",
			"rhs_30Rnd_545x39_7N6M_AK",
			"rhs_30Rnd_545x39_7N10_camo_AK",
			"rhs_30Rnd_545x39_7N22_camo_AK",
			"rhs_30Rnd_545x39_7N10_desert_AK",
			"rhs_30Rnd_545x39_7N22_desert_AK",
			"rhs_30Rnd_545x39_7N6_green_AK",
			"rhs_30Rnd_545x39_7N6M_green_AK",
			"rhs_30Rnd_545x39_AK_plum_green",
			"rhs_30Rnd_545x39_7N10_plum_AK",
			"rhs_30Rnd_545x39_7N22_plum_AK",
			"rhs_30Rnd_545x39_7N6M_plum_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N22_AK",
			"rhs_30Rnd_545x39_7U1_AK",
			"rhs_30Rnd_762x39mm_bakelite",
			"rhs_30Rnd_762x39mm_bakelite_89",
			"rhs_30Rnd_762x39mm_bakelite_tracer",
			"rhs_30Rnd_762x39mm_bakelite_U",
			"rhs_30Rnd_762x39mm_89",
			"rhs_30Rnd_762x39mm_tracer",
			"rhs_30Rnd_762x39mm_U",
			"rhs_mag_30Rnd_556x45_M855A1_EPM_Pull",
			"rhs_mag_30Rnd_556x45_M855A1_EPM_Pull_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_EPM_Ranger",
			"rhs_mag_30Rnd_556x45_M855A1_EPM_Ranger_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_EPM",
			"rhs_mag_30Rnd_556x45_M855A1_EPM_Tracer_Red",
			"rhssaf_30rnd_556x45_TDIM_G36",
			"rhssaf_30rnd_556x45_EPR_G36",
			"rhssaf_30rnd_556x45_MDIM_G36",
			"rhssaf_30rnd_556x45_Tracers_G36",
			"rhssaf_30rnd_556x45_SPR_G36",
			"rhssaf_30rnd_556x45_SOST_G36",
			"rhsgref_30rnd_556x45_m21",
			"rhsgref_30rnd_556x45_m21_t",
			"rhssaf_30Rnd_762x39mm_M67",
			"rhssaf_30Rnd_762x39mm_M78_tracer",
			"rhssaf_30Rnd_762x39_M82_api",
			"rhs_mag_30Rnd_556x45_M855_PMAG_Tan",
			"rhs_mag_30Rnd_556x45_M855_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_Mk262_PMAG_Tan",
			"rhs_mag_30Rnd_556x45_Mk262_PMAG",
			"rhs_mag_30Rnd_556x45_Mk318_PMAG",
			"rhs_30Rnd_762x39mm_Savz58",
			"rhs_30Rnd_762x39mm_Savz58_tracer",
			"rhs_mag_30Rnd_556x45_Mk318_SCAR_Pull",
			"rhs_mag_30Rnd_556x45_Mk318_SCAR_Ranger",
			"rhs_mag_30Rnd_556x45_Mk318_SCAR",
			"rhs_mag_30Rnd_556x45_M855_Stanag_Pull",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",
			"rhs_mag_30Rnd_556x45_M855_Stanag_Pull_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull_Tracer_Red",
			"rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag_Pull",
			"rhs_mag_30Rnd_556x45_M855_Stanag_Ranger",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger",
			"rhs_mag_30Rnd_556x45_M855_Stanag_Ranger_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Ranger_Tracer_Red",
			"rhs_mag_30Rnd_556x45_Mk262_Stanag_Ranger",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag_Ranger",
			"rhs_mag_30Rnd_556x45_M193_Stanag",
			"rhs_mag_30Rnd_556x45_M196_Stanag_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M200_Stanag",
			"rhs_mag_30Rnd_556x45_M855_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhs_mag_30Rnd_556x45_Mk262_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhsgref_30rnd_556x45_vhs2",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsusf_mag_40Rnd_46x30_AP",
			"rhsusf_mag_40Rnd_46x30_FMJ",
			"rhsusf_mag_40Rnd_46x30_JHP",
			"rhs_mag_9x19mm_7n21_44",
			"rhs_mag_9x19mm_7n31_44",
			"Exile_Magazine_6Rnd_45ACP",
			"6Rnd_45ACP",
			"rhs_45Rnd_545X39_AK_Green",
			"rhs_45Rnd_545X39_7N10_AK",
			"rhs_45Rnd_545X39_7N22_AK",
			"rhs_45Rnd_545X39_7N6_AK",
			"rhs_45Rnd_545X39_7U1_AK",
			"45Rnd_Green_Tracer_545x39_RPK",
			"Exile_Magazine_30Rnd_545x39_AK",
			"30Rnd_545x39_Mag_Green_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_Tracer_Green_F",
			"Exile_Magazine_30Rnd_545x39_AK_Green",
			"Exile_Magazine_30Rnd_545x39_AK_Red",
			"Exile_Magazine_30Rnd_545x39_AK_White",
			"30Rnd_545x39_Mag_Tracer_F",
			"Exile_Magazine_30Rnd_545x39_AK_Yellow",
			"Exile_Magazine_45Rnd_545x39_RPK_Green",
			"Exile_Magazine_75Rnd_545x39_RPK_Green",
			"150Rnd_556x45_Drum_Green_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Sand_Mag_F",
			"150Rnd_556x45_Drum_Green_Mag_Tracer_F",
			"150Rnd_556x45_Drum_Mag_Tracer_F",
			"150Rnd_556x45_Drum_Sand_Mag_Tracer_F",
			"200Rnd_556x45_Box_Red_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_Tracer_Red_F",
			"200Rnd_556x45_Box_Tracer_F",
			"20Rnd_556x45_UW_mag",
			"30Rnd_556x45_Stanag_green",
			"30Rnd_556x45_Stanag_Sand_green",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_Sand_red",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Sand",
			"30Rnd_556x45_Stanag_Tracer_Green",
			"30Rnd_556x45_Stanag_Sand_Tracer_Green",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Sand_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Yellow",
			"30Rnd_556x45_Stanag_Sand_Tracer_Yellow",
			"50Rnd_570x28_SMG_03",
			"100Rnd_580x42_ghex_Mag_F",
			"100Rnd_580x42_hex_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_ghex_Mag_Tracer_F",
			"100Rnd_580x42_hex_Mag_Tracer_F",
			"100Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"rhsgref_50Rnd_792x57_SmE_drum",
			"rhsgref_50Rnd_792x57_SmE_notracers_drum",
			"rhsgref_50Rnd_792x57_SmK_drum",
			"rhsgref_50Rnd_792x57_SmK_alltracers_drum",
			"rhsusf_50Rnd_762x51_m82_blank",
			"rhsusf_50Rnd_762x51_m61_ap",
			"rhsusf_50Rnd_762x51_m62_tracer",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51_m80a1epr",
			"50Rnd_UK59_762x54_Tracer_Green",
			"rhsgref_5Rnd_762x54_m38",
			"rhsgref_5Rnd_792x57_kar98k",
			"rhsusf_5Rnd_00Buck",
			"rhsusf_5Rnd_300winmag_xm2010",
			"rhsusf_5Rnd_Slug",
			"rhsusf_5Rnd_762x51_AICS_m118_special_Mag",
			"rhsusf_5Rnd_762x51_AICS_m62_Mag",
			"rhsusf_5Rnd_762x51_AICS_m993_Mag",
			"rhsusf_5Rnd_762x51_m118_special_Mag",
			"rhsusf_5Rnd_762x51_m62_Mag",
			"rhsusf_5Rnd_762x51_m993_Mag",
			"rhs_5Rnd_338lapua_t5000",
			"5Rnd_127x108_APDS_KSVK",
			"5Rnd_127x108_KSVK",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_black_mag_tracer",
			"100Rnd_65x39_caseless_khaki_mag_tracer",
			"200Rnd_65x39_cased_Box_Red",
			"20Rnd_650x39_Cased_Mag_F",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag_Tracer",
			"30Rnd_65x39_caseless_green_mag_Tracer",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"30Rnd_65x39_caseless_khaki_mag_Tracer",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag_Tracer",
			"200Rnd_65x39_cased_Box_Tracer_Red",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box_Tracer",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_mag_Tracer",
			"6Rnd_GreenSignal_F",
			"6Rnd_RedSignal_F",
			"rhs_mag_6x8mm_mhp",
			"Exile_Magazine_100Rnd_762x54_PK_Green",
			"10Rnd_762x54_Mag",
			"10Rnd_762x51_Mag",
			"10Rnd_Mk14_762x51_Mag",
			"150Rnd_762x54_Box_Tracer",
			"Exile_Magazine_20Rnd_762x51_DMR",
			"Exile_Magazine_20Rnd_762x51_DMR_Green",
			"Exile_Magazine_20Rnd_762x51_DMR_Red",
			"Exile_Magazine_20Rnd_762x51_DMR_Yellow",
			"30rnd_762x39_AK12_Lush_Mag_F",
			"30Rnd_762x39_AK12_Mag_F",
			"30rnd_762x39_AK12_Arid_Mag_F",
			"30rnd_762x39_AK12_Lush_Mag_Tracer_F",
			"30Rnd_762x39_AK12_Mag_Tracer_F",
			"30rnd_762x39_AK12_Arid_Mag_Tracer_F",
			"30Rnd_762x39_Mag_Green_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_Tracer_Green_F",
			"30Rnd_762x39_Mag_Tracer_F",
			"Exile_Magazine_30Rnd_762x39_AK",
			"75rnd_762x39_AK12_Arid_Mag_F",
			"75rnd_762x39_AK12_Lush_Mag_F",
			"75rnd_762x39_AK12_Mag_F",
			"75rnd_762x39_AK12_Arid_Mag_Tracer_F",
			"75rnd_762x39_AK12_Lush_Mag_Tracer_F",
			"75rnd_762x39_AK12_Mag_Tracer_F",
			"75Rnd_762x39_Mag_F",
			"75Rnd_762x39_Mag_Tracer_F",
			"150Rnd_762x54_Box",
			"150Rnd_762x51_Box",
			"150Rnd_762x51_Box_Tracer",
			"20Rnd_762x51_Mag",
			"Exile_Magazine_10Rnd_765x17_SA61",
			"Exile_Magazine_20Rnd_765x17_SA61",
			"rhs_75Rnd_762x39mm",
			"rhs_75Rnd_762x39mm_89",
			"rhs_75Rnd_762x39mm_tracer",
			"75Rnd_Green_Tracer_545x39_RPK",
			"Exile_Magazine_10Rnd_762x54",
			"rhsusf_mag_7x45acp_MHP",
			"7Rnd_45ACP_1911",
			"7Rnd_45ACP_1911",
			"rhsgref_8Rnd_762x63_Tracer_M1T_M1rifle",
			"rhsgref_8Rnd_762x63_M2B_M1rifle",
			"rhsusf_8Rnd_Slug",
			"rhs_mag_9x18_8_57N181S",
			"rhs_mag_762x25_8",
			"10Rnd_9x21_Mag",
			"16Rnd_9x21_green_Mag",
			"16Rnd_9x21_red_Mag",
			"16Rnd_9x21_yellow_Mag",
			"30Rnd_9x21_Green_Mag",
			"30Rnd_9x21_Mag_SMG_02_Tracer_Green",
			"30Rnd_9x21_Red_Mag",
			"30Rnd_9x21_Mag_SMG_02_Tracer_Red",
			"30Rnd_9x21_Mag_SMG_02_Tracer_Yellow",
			"30Rnd_9x21_Yellow_Mag",
			"Exile_Magazine_8Rnd_9x18",
			"Exile_Magazine_10Rnd_93x64_DMR_05_Bullet_Cam_Mag",
			"10Rnd_93x64_DMR_05_Mag",
			"16Rnd_9x21_Mag",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag",
			"Exile_Magazine_10Rnd_9x39",
			"Exile_Magazine_20Rnd_9x39",
			"30Rnd_762x39_AK47_M",
			"30Rnd_545x39_AK",
			"30Rnd_Green_Tracer_545x39_AK",
			"30Rnd_Red_Tracer_545x39_AK",
			"30Rnd_White_Tracer_545x39_AK",
			"30Rnd_Yellow_Tracer_545x39_AK",
			"Exile_Magazine_5Rnd_127x108_APDS_KSVK",
			"5x_22_LR_17_HMR_M",
			"10x_303_M",
			"8Rnd_B_Beneli_74Pellets",
			"8rnd_B_Beneli_74Slug",
			"8Rnd_9x18_Makarov",
			"8Rnd_9x18_MakarovSD",
			"Exile_Magazine_8Rnd_74Pellets",
			"100Rnd_762x54_PK_Tracer_Green",
			"100Rnd_762x54_PK_Tracer_Red",
			"100Rnd_762x54_PK_Tracer_White",
			"100Rnd_762x54_PK_Tracer_Yellow",
			"10Rnd_765x17ball",
			"20Rnd_765x17ball",
			"Exile_Magazine_8Rnd_74Slug",
			"10Rnd_9x39_VSS",
			"20Rnd_9x39_VSS"
		};
	};

	class Rockets
	{
		name = "Rockets";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargothrow_ca.paa";
		items[] =
		{
				"rhs_mag_2Rnd_Igla",
				"rhs_mag_9k38_rocket",
				"Vorona_HE",
				"Vorona_HEAT",
				"rhs_mag_maaws_HE",
				"rhs_mag_maaws_HEDP",
				"rhs_mag_maaws_HEAT",
				"rhs_fim92_mag",
				"rhs_fgm148_magazine_AT",
				"MRAWS_HE_F",
				"MRAWS_HEAT55_F",
				"MRAWS_HEAT_F",
				"rhs_mag_smaw_HEDP",
				"rhs_mag_smaw_HEAA",
				"rhs_rpg7_OG7V_mag",
				"rhs_rpg7_PG7V_mag",
				"rhs_rpg7_PG7VL_mag",
				"rhs_rpg7_PG7VM_mag",
				"RPG7_F",
				"rhs_rpg7_PG7VR_mag",
				"rhs_rpg7_PG7VS_mag",
				"RPG32_HE_F",
				"RPG32_F",
				"rhs_rpg7_TBG7V_mag",
				"Titan_AA",
				"Titan_AP",
				"Titan_AT",
				"rhs_rpg7_type69_airburst_mag",
		};
	};
	
	class Explosives
	{
		name = "Grenades";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargothrow_ca.paa";
		items[] =
		{
			"3Rnd_UGL_FlareGreen_F",						
			"3Rnd_UGL_FlareCIR_F",
			"3Rnd_UGL_FlareRed_F",
			"3Rnd_UGL_FlareWhite_F",
			"3Rnd_UGL_FlareYellow_F",
			"3Rnd_SmokeBlue_Grenade_shell",
			"3Rnd_SmokeGreen_Grenade_shell",
			"3Rnd_SmokeOrange_Grenade_shell",
			"3Rnd_SmokePurple_Grenade_shell",
			"3Rnd_SmokeRed_Grenade_shell",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_SmokeYellow_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"rhsusf_mag_6Rnd_M397_HET",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M441_HE",
			"rhsusf_mag_6Rnd_m4009",
			"rhsusf_mag_6Rnd_M576_Buckshot",
			"rhsusf_mag_6Rnd_M585_white",
			"rhsusf_mag_6Rnd_m661_green",
			"rhsusf_mag_6Rnd_m662_red",
			"rhsusf_mag_6Rnd_M713_red",
			"rhsusf_mag_6Rnd_M714_white",
			"rhsusf_mag_6Rnd_M715_green",
			"rhsusf_mag_6Rnd_M716_yellow",
			"rhsusf_mag_6Rnd_M781_Practice",
			"FlareGreen_F",
			"FlareRed_F",
			"FlareWhite_F",
			"FlareYellow_F",
			"UGL_FlareGreen_F",
			"rhs_mag_rsp30_green",
			"UGL_FlareCIR_F",
			"UGL_FlareRed_F",
			"rhs_mag_rsp30_red",
			"rhs_mag_rsp30_white",
			"UGL_FlareWhite_F",
			"UGL_FlareYellow_F",
			"rhs_GDM40",
			"rhs_mag_m4009",
			"rhs_GRD40_Green",
			"rhs_GRD40_Red",
			"rhs_GRD40_White",
			"rhs_mag_M397_HET",
			"rhs_mag_M433_HEDP",
			"rhs_mag_M441_HE",
			"rhs_mag_m576",
			"rhs_mag_M585_white",
			"rhs_mag_m661_green",
			"rhs_mag_m662_red",
			"rhs_mag_m713_Red",
			"rhs_mag_m714_White",
			"rhs_mag_m715_Green",
			"rhs_mag_m716_yellow",
			"rhs_mag_M781_Practice",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"rhs_VG40MD",
			"rhs_VG40OP_green",
			"rhs_VG40OP_red",
			"rhs_VG40OP_white",
			"rhs_VG40SZ",
			"rhs_VG40TB",
			"rhs_VOG25",
			"rhs_VOG25P",
			"DemoCharge_Remote_Mag",
			"SatchelCharge_Remote_Mag",
			"SmokeShell",
			"SmokeShellBlue",
			"SmokeShellGreen",
			"SmokeShellOrange",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellYellow",
			"MiniGrenade",
			"HandGrenade",
			"Chemlight_blue",
			"Chemlight_green",
			"Chemlight_red"
		};
	};

	class Pistols
	{
		name = "Pistols";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";
		items[] =
		{
			"Exile_Weapon_Colt1911",
			"Exile_Weapon_Makarov",
			"Exile_Weapon_SA61",
			"Exile_Weapon_Taurus",
			"Exile_Weapon_TaurusGold",
			"hgun_Pistol_heavy_02_F",
			"hgun_ACPC2_F",
			"hgun_Pistol_heavy_01_F",
			"hgun_Rook40_F",
			"hgun_P07_F",
			"hgun_Pistol_Signal_F",
			"hgun_Pistol_01_F",
			"hgun_P07_khk_F",
			"hgun_Pistol_heavy_01_green_F",
			"rhs_weap_6p53",
			"rhs_weap_pb_6p9",
			"rhs_weap_pya",
			"rhs_weap_makarov_pm",
			"rhs_weap_pp2000_folded",
			"rhsusf_weap_glock17g4",
			"rhsusf_weap_m1911a1",
			"rhs_weap_M320",
			"rhsusf_weap_m9",
			"rhs_weap_savz61_folded",
			"rhs_weap_tt33",
			"rhs_weap_type94_new",
		};
	};

	class SubMachineGuns
	{
		name = "Sub Machine Guns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"hgun_PDW2000_F",
			"SMG_03C_black",
			"SMG_03_black",
			"SMG_03C_TR_black",
			"SMG_03_TR_black",
			"SMG_01_F",
			"SMG_02_F",
			"SMG_05_F",
			"rhsusf_weap_MP7A2",
			"rhs_weap_m3a1",
			"rhs_weap_savz61",
			"rhs_weap_scorpion"
		};
	};

	class LightMachineGuns
	{
		name = "Light Machine Guns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Weapon_PK",
			"Exile_Weapon_PKP",
			"Exile_Weapon_RPK",
			"arifle_MX_SW_F",
			"arifle_MX_SW_Black_F",
			"LMG_Mk200_F",
			"MMG_01_hex_F",
			"MMG_01_tan_F",
			"MMG_02_black_F",
			"MMG_02_camo_F",
			"MMG_02_sand_F",
			"LMG_03_F",
			"arifle_MX_SW_khk_F",
			"arifle_CTARS_blk_F",
			"arifle_CTARS_ghex_F",
			"arifle_CTARS_hex_F",
			"arifle_RPK12_F",
			"arifle_RPK12_arid_F",
			"arifle_RPK12_lush_F",
			"LMG_Mk200_black_F",
			"rhs_weap_pkm",
			"rhs_weap_pkp",
			"rhs_weap_m240B",
			"rhs_weap_m249",
			"rhs_weap_m249_pip",
			"rhs_weap_m249_pip_ris"
		};
	};

	class AssaultRifles
	{
		name = "Assault Rifles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Weapon_AK107",
			"Exile_Weapon_AK107_GL",
			"Exile_Weapon_AK47",
			"Exile_Weapon_AK74",
			"Exile_Weapon_AK74_GL",
			"Exile_Weapon_AKM",
			"Exile_Weapon_AKS",
			"Exile_Weapon_AKS_Gold",
			"Exile_Weapon_M16A2",
			"Exile_Weapon_M16A4",
			"Exile_Weapon_M4",
			"arifle_TRG20_F",
			"arifle_Mk20_plain_F",
			"arifle_Mk20_F",
			"arifle_Mk20_GL_plain_F",
			"arifle_Mk20_GL_F",
			"arifle_Mk20C_plain_F",
			"arifle_Mk20C_F",
			"arifle_TRG21_GL_F",
			"arifle_Katiba_F",
			"arifle_Katiba_GL_F",
			"arifle_Katiba_C_F",
			"arifle_MX_F",
			"arifle_MX_Black_F",
			"arifle_MX_GL_F",
			"arifle_MX_GL_Black_F",
			"arifle_MXC_F",
			"arifle_MXC_Black_F",
			"arifle_TRG21_F",
			"arifle_SDAR_F",
			"arifle_AK12_F",
			"arifle_AK12_GL_F",
			"arifle_AKM_F",
			"arifle_AKS_F",
			"arifle_SPAR_01_blk_F",
			"arifle_SPAR_01_khk_F",
			"arifle_SPAR_01_snd_F",
			"arifle_SPAR_01_GL_blk_F",
			"arifle_SPAR_01_GL_khk_F",
			"arifle_SPAR_01_GL_snd_F",
			"arifle_SPAR_02_blk_F",
			"arifle_SPAR_02_khk_F",
			"arifle_SPAR_02_snd_F",
			"arifle_SPAR_03_blk_F",
			"arifle_SPAR_03_khk_F",
			"arifle_SPAR_03_snd_F",
			"arifle_MX_GL_khk_F",
			"arifle_MX_khk_F",
			"arifle_MX_SW_khk_F",
			"arifle_MXC_khk_F",
			"arifle_CTAR_blk_F",
			"arifle_CTAR_ghex_F",
			"arifle_CTAR_hex_F",
			"arifle_CTAR_GL_blk_F",
			"arifle_CTAR_GL_ghex_F",
			"arifle_CTAR_GL_hex_F",
			"arifle_AK12_lush_F",
			"arifle_AK12U_lush_F",
			"arifle_MSBS65_F",
			"arifle_MSBS65_GL_F",
			"arifle_MSBS65_UBS_F",
			"rhs_weap_ak103",
			"rhs_weap_ak74_3",
			"rhs_weap_ak74m_gp25",
			"rhs_weap_akm",
			"rhs_weap_aks74n",
			"rhs_weap_asval",
			"rhs_weap_aks74u",
			"rhs_weap_vss",
			"rhs_weap_hk416d10",
			"rhs_weap_hk416d10_m320",
			"rhs_weap_hk416d145",
			"rhs_weap_m16a4",
			"rhs_weap_m16a4_imod_M203",
			"rhs_weap_m4",
			"rhs_weap_m27iar",
			"rhs_weap_m4_carryhandle_m203S",
			"rhs_weap_m4a1_blockII",
			"rhs_weap_m4a1_blockII_d",
			"rhs_weap_m4a1_m203",
			"rhs_weap_m4a1_mstock",
			"rhs_weap_mk17_CQC",
			"rhs_weap_mk18",
			"rhs_weap_mk18_bk",
			"rhs_weap_SCARH_USA_CQC",
			"rhs_weap_m21s",
			"rhs_weap_m70ab2",
			"rhs_weap_savz58p",
			"rhs_weap_vhsd2",
			"rhs_weap_savz58v_ris",
			"rhs_weap_g36c",
			"rhs_weap_SCARH_LB",
			"arifle_ARX_blk_F"
			
		};
	};

	class Shotguns
	{
		name = "Shotguns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Weapon_M1014",
			//"sgun_HunterShotgun_01_F", //not working (can't buy)
			"sgun_HunterShotgun_01_sawedoff_F",
			"rhs_weap_M590_8RD",
			"rhs_weap_M590_5RD"
		};
	};

	class SniperRifles
	{
		name = "Sniper Rifles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Weapon_CZ550",
			"Exile_Weapon_DMR",
			"Exile_Weapon_LeeEnfield",
			"Exile_Weapon_SVD",
			"Exile_Weapon_SVDCamo",
			"Exile_Weapon_VSSVintorez",
			"Exile_weapon_ksvk",
			"Exile_Weapon_m107",
			"srifle_GM6_F",
			"srifle_GM6_camo_F",
			"srifle_LRR_F",
			"srifle_LRR_camo_F",
			"srifle_EBR_F",
			"arifle_MXM_F",
			"arifle_MXM_Black_F",
			"srifle_DMR_01_F",
			"srifle_DMR_04_F",
			"srifle_DMR_04_Tan_F",
			"srifle_DMR_05_blk_F",
			"srifle_DMR_05_hex_F",
			"srifle_DMR_05_tan_f",
			"srifle_DMR_06_camo_F",						
			"srifle_DMR_06_olive_F",					
			"srifle_DMR_02_F",
			"srifle_DMR_02_camo_F",
			"srifle_DMR_02_sniper_F",
			"srifle_DMR_03_F",
			"srifle_DMR_03_multicam_F",
			"srifle_DMR_03_khaki_F",
			"srifle_DMR_03_tan_F",
			"srifle_DMR_03_woodland_F",
			"srifle_GM6_ghex_F",
			"srifle_LRR_tna_F",
			"srifle_DMR_07_blk_F",
			"srifle_DMR_07_ghex_F",
			"srifle_DMR_07_hex_F",
			"srifle_DMR_06_hunter_F",
			"rhs_weap_svdp",
			"rhs_weap_M107",
			"rhs_weap_XM2010",
			"rhs_weap_m24sws",
			"rhs_weap_m40a5",
			"rhs_weap_sr25",
			"rhs_weap_m1garand_sa43",
			"rhs_weap_m38"
		};
	};

	class Bikes
	{
		name = "Bikes";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Bike_OldBike",
			"Exile_Bike_MountainBike"
		};
	};

	class Cars
	{
		name = "Cars";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"rhsusf_rg33_d",
			"Exile_Car_Golf_Black",
			"Exile_Car_TowTractor_White",
			"Exile_Car_LandRover_Ambulance_Desert",
			"Exile_Car_Lada_Green",
			"Exile_Car_Volha_White",
			"Exile_Car_HMMWV_MEV_Desert",
			"Exile_Car_HMMWV_UNA_Desert",
			"Exile_Car_BTR40_Camo",
			"Exile_Car_BTR40_Green",
			"Exile_Car_SUV_Black",
			"Exile_Car_LandRover_Desert",
			"Exile_Car_UAZ_Open_Green",
			"Exile_Car_UAZ_Green",
			"Exile_Car_Octavius_White",
			"Exile_Car_Tractor_Red",
			"Exile_Car_OldTractor_Red",
			"Exile_Car_SUVXL_Black",
			"rhs_tigr_ffv_msv",
			"rhs_tigr_m_msv",
			"rhsusf_m1025_d",
			"rhsusf_m998_d_2dr",
			"rhsusf_m998_d_2dr_fulltop",
			"rhsusf_m998_d_2dr_halftop",
			"rhsusf_m998_d_4dr",
			"B_T_LSV_01_unarmed_F",
			"C_Offroad_02_unarmed_F",
			"O_T_LSV_02_unarmed_F",
			"B_MRAP_01_F",
			"B_Quadbike_01_F",
			"C_Hatchback_01_F",
			"C_Kart_01_Blu_F",
			"C_Offroad_01_F",
			"C_SUV_01_F",
			"I_MRAP_03_F",
			"O_MRAP_02_F",
			"RHS_UAZ_MSV_01"
			
		};
	};
	
	class ArmedCars
	{
		name = "Armed Cars";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Car_HMMWV_M134_Desert",
			"Exile_Car_HMMWV_M2_Desert",
			"Exile_Car_BTR40_MG_Green",
			"Exile_Car_BRDM2_HQ",
			"Exile_Car_SUV_Armed_Black",
			"rhs_tigr_sts_msv",
			"rhsusf_m1025_d_m2",
			"B_T_LSV_01_armed_F",
			"O_T_LSV_02_armed_black_F",
			"rhsgref_cdf_reg_uaz_dshkm",
			"rhsusf_m1240a1_m2_iscm_d",
			"rhsgref_BRDM2UM_vmf",
			"rhsgref_BRDM2_vmf",
			"rhs_btr60_vdv",
			"rhsgref_un_btr70"
		};
	};

	class Trucks
	{
		name = "Trucks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Car_Ural_Covered_Blue",
			"Exile_Car_Ural_Open_Blue",
			"Exile_Car_Ikarus_Blue",
			"Exile_Car_V3S_Open",
			"Exile_Car_V3S_Covered",
			"O_Truck_03_transport_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_ammo_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_transport_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_box_F",
			"B_Truck_01_ammo_F",
			"B_Truck_01_Repair_F",
			"C_Van_01_transport_F",
			"C_Van_01_fuel_F",
			"rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy",
			"rhs_kamaz5350_open",
			"rhs_kamaz5350",
			"RHS_Ural_Repair_MSV_01",
			"RHS_Ural_Open_Civ_01",
			"RHS_Ural_Fuel_MSV_01",
			"RHS_Ural_Civ_01",
			"RHS_Civ_Truck_02_transport_F",
			"C_Van_01_box_F",
			"I_Truck_02_ammo_F",
			"C_Truck_02_transport_F",
			"C_Truck_02_fuel_F",
			"C_Truck_02_covered_F"
		};
	};
	
	class ArmedTrucks
	{
		name = "Armed Trucks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1078A1R_SOV_M2_D_fmtv_socom"
		};
	};

	class Choppers
	{
		name = "Helicopters";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			
			"rhsusf_CH53E_USMC", //CH53E unarmed
			"I_Heli_light_03_unarmed_F", //wildcard unarmed
			"RHS_UH60M2", //Blackhook unarmed
			"RHS_Mi8AMT_vdv", //Mi8 unarmed
			"RHS_UH1Y_UNARMED_d", //moderní hu-yuík unarmed 
			"B_Heli_Light_01_F", //hummibird unarmed
			"C_Heli_Light_01_civil_F", //civilní hummibird
			"O_Heli_Light_02_unarmed_F", //kosatka unarmed
			"O_Heli_Transport_04_F", //taru empty
			"O_Heli_Transport_04_ammo_F", //ammo
			"O_Heli_Transport_04_bench_F", //bench
			"O_Heli_Transport_04_box_F", //cargo
			"O_Heli_Transport_04_fuel_F", //Fuel
			"O_Heli_Transport_04_repair_F", //repair
			"I_Heli_Transport_02_F" //Merlin unarmed
		};
	};
	
	class ArmedChoppers
	{
		name = "Armed Helicopters";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"B_Heli_Transport_01_F", //Ghosthawk armed
			"RHS_CH_47F", //RHS chinook armed
			"I_Heli_light_03_F", //Wildcard armed
			"O_Heli_Light_02_F", //kosatka armed
			"B_Heli_Transport_03_F", //Arma chinook armed
			"RHS_UH1Y", //moderní hu-yuík armed
			"RHS_MELB_AH6M", //littlebird armed
			"RHS_Mi8mt_vdv", //Mi8 door gunner
			"RHS_UH60M" //Blackhook armed
		};
	};

	class Boats
	{
		name = "Boats";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"rhs_bkm_t",
			"C_Scooter_Transport_01_F", //skůtr
			"I_C_Boat_Transport_02_F", //člun s kormidlem
			"B_Boat_Transport_01_F", //člun motor
			"B_Lifeboat", //lifeboat
			"B_SDV_01_F", //ponorka
			"C_Boat_Civil_01_F", //civilní loďka
			"I_Boat_Armed_01_minigun_F" //armed with minigun
		};
	};

	class Planes
	{
		name = "Planes";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"B_T_VTOL_01_infantry_F", //NATO VTOL unarmed
			"GNT_C185T", //exile letadlo armed
			"GNT_C185", //exile letadlo unarmed
			"C_Plane_Civil_01_F", //arma 3 civilní letadlo
			"rhs_l39_cdf", //jet only CAS rockets
			"RHS_AN2", //rhs transport plane
			"RHS_C130J" //RHS huge transport plane
		};
	};

	class Diving
	{
		name = "Diving";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"G_Diving",
			"G_I_Diving",
			"G_O_Diving",
			"G_B_Diving",
			"U_I_Wetsuit",
			"U_O_Wetsuit",
			"U_B_Wetsuit",
			"Exile_Uniform_Wetsuit_AAF",
			"Exile_Uniform_Wetsuit_CSAT",
			"Exile_Uniform_Wetsuit_NATO",
			"V_RebreatherIA",
			"V_RebreatherIR",
			"V_RebreatherB",
			"Exile_Vest_Rebreather_AAF",
			"Exile_Vest_Rebreather_NATO",
			"Exile_Vest_Rebreather_CSAT",
		};
	};
	
	class Launchers
	{
		name = "Launchers";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"rhs_weap_M136",
			"rhs_weap_rpg7"
		};
	};
	
	class Track
	{
		name = "Armored";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"rhs_sprut_vdv",
			"rhsusf_m113d_usarmy",
			"rhsusf_m113d_usarmy_unarmed",
			"rhs_pts_vmf"
		};
	};